In [2]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
print(a[1:])
print(a[:-2])
print(type(a))
print(a[1:3])
print(a[:3])
print(a[-3:-1])

a[2] = 10
print(a)


[1 2 3 4 5]
[2 3 4 5]
[1 2 3]
<class 'numpy.ndarray'>
[2 3]
[1 2 3]
[3 4]
[ 1  2 10  4  5]


In [15]:
a_mul = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(a_mul[0])
print("3rd element on first row: " , a_mul[0 , 2])

arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(a))

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3rd element in the 2nd row of first column: " , arr[0, 1, 2])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

[1 2 3]
3rd element on first row:  3
[1 2 3 4 5]
<class 'numpy.ndarray'>
3rd element in the 2nd row of first column:  6
Last element from 2nd dim:  10


In [11]:
a = np.array(42)                                                # 0-D Array
b = np.array([1, 2, 3, 4, 5])                                   # 1-D Array
c = np.array([[1, 2, 3], [4, 5, 6]])                            # 2-D Array
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])  # 3-D Array
arr = np.array([1, 2, 3, 4], ndmin=5)                           # 5-D Array
 
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(arr.ndim)

0
1
2
3
5


In [26]:
# Step to determine the value of slicing

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:10:2])
print(arr[::2]) # Return every other element from the entire array


# Slicing 2D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

# From both elements, return index 2
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[ 2  4  6  8 10]
[1 3 5 7 9]
[7 8 9]
[3 8]


In [33]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 2, 3)
3
12
int32


In [36]:
a1 = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])
print(a1.dtype)
print(a1[0][0].dtype)

a2 = np.array([[1, 2, 3], 
              [4, "5", 6],
              [7, 8, 9]])
print(a2.dtype)
print(a2[0][0].dtype)

a3 = np.array([[1, 2, 3], 
              [4, "5", 6],
              [7, 8, 9]], dtype= np.float32)
print(a3.dtype)
print(a3[1][1].dtype)

int32
int32
<U11
<U1
float32
float32


In [42]:
d = {"1" : "A"}

a1 = np.array([[1, 2, 3], 
              [4, d, 6],
              [7, 8, 9]])
print(a1.dtype)

object


In [43]:
a = np.full((2,2,3), 9)
print(a)

[[[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]]


In [46]:
x_values = np.arange(0, 1001, 5) # Gives the range from 0 to 1000 with a step of 5
print(x_values)

x_values = np.linspace(0, 1000, 5) # Divides the range into 5 equal parts
print(x_values)


[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

In [47]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 10]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1 * 5)
print(a1 * 5)

print(l1 + l2)
print(a1 + a2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 7  9 11 13 15]


In [49]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1],
               [2]])

print(a1 + a2)

[[5 6 7]
 [4 5 6]]


In [51]:
a = np.array([1, 2, 3, 4, 5])
print(np.append(a, [6, 7, 8]))
print(a)

a = np.append(a, [6, 7, 8])
print(a)

a = np.insert(a, 8, [9, 10])
print(a)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5]
[1 2 3 4 5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(np.delete(a, 1))
print(np.delete(a, 3))

print(np.delete(a, 1, 0))
print(np.delete(a, 0, 0))
print(np.delete(a, 1, 1))

# Delete works according to the order of the matrix

[1 3 4 5 6]
[1 2 3 5 6]
[[1 2 3]]
[[4 5 6]]
[[1 3]
 [4 6]]


In [55]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],])

print(a.shape)
print(a.reshape(5, 4))
print(a.reshape(20,))
print(a.reshape(20, 1))
print(a.reshape(2, 10))
print(a.reshape(2, 2, 5))
print(a.reshape(2, 5, 2))
print(a.reshape(5, 2, 2))

(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [56]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],])

a.reshape((10, 2))
print(a)

a.resize((10, 2))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [58]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],])

print(a.flatten()) 
print(a.ravel())

var1 = a.flatten()
var1[2] = 100
print(var1)
print(a)

var2 = a.ravel()
var2[2] = 100
print(var2)
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2 100   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [59]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],])

print(a.transpose())
print(a.T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [60]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],])
print(a.swapaxes(0, 1)) # Used in higher dimensional arrays

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [64]:
a1 = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10]])

a2 = np.array([[11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

a = np.concatenate((a1, a2), axis=0)
print(a)

a = np.concatenate((a1, a2), axis=1)
print(a)

a = np.stack((a1, a2))
print(a)

a = np.vstack((a1, a2))
print(a)

a = np.hstack((a1, a2))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [68]:
a1 = np.array([ [1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

print(np.split(a, 2, axis=0))

[array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15]]), array([[ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])]


In [70]:
a1 = np.array([ [1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())
print(np.median(a))

1
20
10.5
5.766281297335398
210
10.5


In [73]:
number = np.random.randint(100)
print(number)

numbers = np.random.randint(100, size=(2,3,4))
print(numbers)

numbers = np.random.randint(90, 100, size=(2,3,4))
print(numbers)


38
[[[60 10  3 70]
  [86 72  7 56]
  [60 21 91 36]]

 [[68 62 47 47]
  [ 7 81 30 65]
  [51 27 45 26]]]
[[[96 93 92 98]
  [94 97 98 97]
  [96 98 91 96]]

 [[96 95 98 91]
  [92 98 94 98]
  [98 95 93 95]]]


In [77]:
numbers = np.random.binomial(10, p=0.5, size=(2,5))
print(numbers)

numbers = np.random.normal(loc = 170, scale = 15, size=(2,5))
print(numbers)

number = np.random.choice([1, 2, 3, 4, 5])
print(number)

number = np.random.choice([1, 2, 3, 4, 5], size=(2,3))
print(number)

[[5 7 4 4 6]
 [5 6 5 6 5]]
[[160.89061067 159.92402498 164.12262158 193.97534763 160.16435044]
 [172.24877471 153.32221749 163.70427633 156.37265727 156.73492442]]
4
[[5 2 1]
 [5 1 2]]


In [3]:
a = np.array([ [1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

np.save("my_array.npy", a)

In [4]:
a = np.load("my_array.npy")
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
a = np.array([ [1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

np.savetxt("my_array.csv", a, delimiter=",")

In [9]:
a = np.loadtxt("my_array.csv", delimiter=",")
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
